export const moviesData = [
    {
        "id": 1,
        "name": "The Shawshank Redemption",
        "img_link": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        "genre": "Drama",
        "rating": 9.3,
        "director_name": "Frank Darabont",
        "writter_name": "Stephen King, Frank Darabont",
        "cast_name": "Tim Robbins, Morgan Freeman",
        "duration": 142,
        "imdb_rating": 9.3
    },
    {
        "id": 2,
        "name": "The Godfather",
        "img_link": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        "genre": "Crime, Drama",
        "rating": 9.2,
        "director_name": "Francis Ford Coppola",
        "writter_name": "Mario Puzo, Francis Ford Coppola",
        "cast_name": "Marlon Brando, Al Pacino",
        "duration": 175,
        "imdb_rating": 9.2
    },
    {
        "id": 3,
        "name": "The Dark Knight",
        "img_link": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
        "genre": "Action, Crime, Drama",
        "rating": 9.0,
        "director_name": "Christopher Nolan",
        "writter_name": "Jonathan Nolan, Christopher Nolan",
        "cast_name": "Christian Bale, Heath Ledger",
        "duration": 152,
        "imdb_rating": 9.0
    },
    {
        "id": 4,
        "name": "Pulp Fiction",
        "img_link": "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        "genre": "Crime, Drama",
        "rating": 8.9,
        "director_name": "Quentin Tarantino",
        "writter_name": "Quentin Tarantino",
        "cast_name": "John Travolta, Samuel L. Jackson",
        "duration": 154,
        "imdb_rating": 8.9
    },
    {
        "id": 5,
        "name": "Inception",
        "img_link": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
        "genre": "Action, Adventure, Sci-Fi",
        "rating": 8.8,
        "director_name": "Christopher Nolan",
        "writter_name": "Christopher Nolan",
        "cast_name": "Leonardo DiCaprio, Joseph Gordon-Levitt",
        "duration": 148,
        "imdb_rating": 8.8
    },
    {
        "id": 6,
        "name": "Interstellar",
        "img_link": "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        "genre": "Adventure, Drama, Sci-Fi",
        "rating": 8.6,
        "director_name": "Christopher Nolan",
        "writter_name": "Jonathan Nolan, Christopher Nolan",
        "cast_name": "Matthew McConaughey, Anne Hathaway",
        "duration": 169,
        "imdb_rating": 8.6
    },
    {
        "id": 7,
        "name": "The Matrix",
        "img_link": "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        "genre": "Action, Sci-Fi",
        "rating": 8.7,
        "director_name": "Lana Wachowski, Lilly Wachowski",
        "writter_name": "Lana Wachowski, Lilly Wachowski",
        "cast_name": "Keanu Reeves, Laurence Fishburne",
        "duration": 136,
        "imdb_rating": 8.7
    },
    {
        "id": 8,
        "name": "Forrest Gump",
        "img_link": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        "genre": "Drama, Romance",
        "rating": 8.8,
        "director_name": "Robert Zemeckis",
        "writter_name": "Winston Groom, Eric Roth",
        "cast_name": "Tom Hanks, Robin Wright",
        "duration": 142,
        "imdb_rating": 8.8
    },
    {
        "id": 9,
        "name": "Fight Club",
        "img_link": "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
        "genre": "Drama, Thriller",
        "rating": 8.8,
        "director_name": "David Fincher",
        "writter_name": "Chuck Palahniuk, Jim Uhls",
        "cast_name": "Brad Pitt, Edward Norton",
        "duration": 139,
        "imdb_rating": 8.8
    },
    {
        "id": 10,
        "name": "Goodfellas",
        "img_link": "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        "genre": "Biography, Crime, Drama",
        "rating": 8.7,
        "director_name": "Martin Scorsese",
        "writter_name": "Nicholas Pileggi, Martin Scorsese",
        "cast_name": "Robert De Niro, Ray Liotta",
        "duration": 146,
        "imdb_rating": 8.7
    },
    {
        "id": 11,
        "name": "The Lord of the Rings: The Return of the King",
        "img_link": "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        "genre": "Action, Adventure, Fantasy",
        "rating": 9.0,
        "director_name": "Peter Jackson",
        "writter_name": "J.R.R. Tolkien, Fran Walsh",
        "cast_name": "Elijah Wood, Viggo Mortensen",
        "duration": 201,
        "imdb_rating": 9.0
    },
    {
        "id": 12,
        "name": "Schindler's List",
        "img_link": "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        "genre": "Biography, Drama, History",
        "rating": 9.0,
        "director_name": "Steven Spielberg",
        "writter_name": "Thomas Keneally, Steven Zaillian",
        "cast_name": "Liam Neeson, Ben Kingsley",
        "duration": 195,
        "imdb_rating": 9.0
    },
    {
        "id": 13,
        "name": "The Silence of the Lambs",
        "img_link": "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        "genre": "Crime, Drama, Thriller",
        "rating": 8.6,
        "director_name": "Jonathan Demme",
        "writter_name": "Thomas Harris, Ted Tally",
        "cast_name": "Jodie Foster, Anthony Hopkins",
        "duration": 118,
        "imdb_rating": 8.6
    },
    {
        "id": 14,
        "name": "Gladiator",
        "img_link": "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        "genre": "Action, Adventure, Drama",
        "rating": 8.5,
        "director_name": "Ridley Scott",
        "writter_name": "David Franzoni, John Logan",
        "cast_name": "Russell Crowe, Joaquin Phoenix",
        "duration": 155,
        "imdb_rating": 8.5
    },
    {
        "id": 15,
        "name": "Saving Private Ryan",
        "img_link": "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg",
        "genre": "Drama, War",
        "rating": 8.6,
        "director_name": "Steven Spielberg",
        "writter_name": "Robert Rodat",
        "cast_name": "Tom Hanks, Matt Damon",
        "duration": 169,
        "imdb_rating": 8.6
    },
    {
        "id": 16,
        "name": "The Green Mile",
        "img_link": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg",
        "genre": "Crime, Drama, Fantasy",
        "rating": 8.6,
        "director_name": "Frank Darabont",
        "writter_name": "Stephen King, Frank Darabont",
        "cast_name": "Tom Hanks, Michael Clarke Duncan",
        "duration": 189,
        "imdb_rating": 8.6
    },
    {
        "id": 17,
        "name": "Spirited Away",
        "img_link": "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        "genre": "Animation, Adventure, Family",
        "rating": 8.6,
        "director_name": "Hayao Miyazaki",
        "writter_name": "Hayao Miyazaki",
        "cast_name": "Daveigh Chase, Suzanne Pleshette",
        "duration": 125,
        "imdb_rating": 8.6
    },
    {
        "id": 18,
        "name": "The Departed",
        "img_link": "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_.jpg",
        "genre": "Crime, Drama, Thriller",
        "rating": 8.5,
        "director_name": "Martin Scorsese",
        "writter_name": "William Monahan, Alan Mak",
        "cast_name": "Leonardo DiCaprio, Matt Damon, Jack Nicholson",
        "duration": 151,
        "imdb_rating": 8.5
    },
    {
        "id": 19,
        "name": "Back to the Future",
        "img_link": "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        "genre": "Adventure, Comedy, Sci-Fi",
        "rating": 8.5,
        "director_name": "Robert Zemeckis",
        "writter_name": "Robert Zemeckis, Bob Gale",
        "cast_name": "Michael J. Fox, Christopher Lloyd",
        "duration": 116,
        "imdb_rating": 8.5
    },
    {
        "id": 20,
        "name": "The Pianist",
        "img_link": "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        "genre": "Biography, Drama, Music",
        "rating": 8.5,
        "director_name": "Roman Polanski",
        "writter_name": "Ronald Harwood, Wladyslaw Szpilman",
        "cast_name": "Adrien Brody, Thomas Kretschmann",
        "duration": 150,
        "imdb_rating": 8.5
    },
    {
        "id": 21,
        "name": "The Usual Suspects",
        "img_link": "https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        "genre": "Crime, Mystery, Thriller",
        "rating": 8.5,
        "director_name": "Bryan Singer",
        "writter_name": "Christopher McQuarrie",
        "cast_name": "Kevin Spacey, Gabriel Byrne",
        "duration": 106,
        "imdb_rating": 8.5
    },
    {
        "id": 22,
        "name": "Whiplash",
        "img_link": "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        "genre": "Drama, Music",
        "rating": 8.5,
        "director_name": "Damien Chazelle",
        "writter_name": "Damien Chazelle",
        "cast_name": "Miles Teller, J.K. Simmons",
        "duration": 106,
        "imdb_rating": 8.5
    },
    {
        "id": 23,
        "name": "Raiders of the Lost Ark",
        "img_link": "https://m.media-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_.jpg",
        "genre": "Action, Adventure",
        "rating": 8.4,
        "director_name": "Steven Spielberg",
        "writter_name": "Lawrence Kasdan, George Lucas",
        "cast_name": "Harrison Ford, Karen Allen",
        "duration": 115,
        "imdb_rating": 8.4
    }

];